//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR_LanguageResource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TR_LanguageResource.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account .
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Cost .
        /// </summary>
        public static string ActualCost {
            get {
                return ResourceManager.GetString("ActualCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add .
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info .
        /// </summary>
        public static string AddInfo {
            get {
                return ResourceManager.GetString("AddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address .
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected affected row count do not match the actual affacted row count, please check the data. Operation canceled..
        /// </summary>
        public static string AffectedRowCountDoesNotMatchExpected {
            get {
                return ResourceManager.GetString("AffectedRowCountDoesNotMatchExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Freight Detail .
        /// </summary>
        public static string AirFreightDetail {
            get {
                return ResourceManager.GetString("AirFreightDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert! .
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Quotation .
        /// </summary>
        public static string AllQuotation {
            get {
                return ResourceManager.GetString("AllQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount .
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To .
        /// </summary>
        public static string ApplyTo {
            get {
                return ResourceManager.GetString("ApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWB No .
        /// </summary>
        public static string AWBNo {
            get {
                return ResourceManager.GetString("AWBNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        public static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Confirmation .
        /// </summary>
        public static string BookingConfirmation {
            get {
                return ResourceManager.GetString("BookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Date .
        /// </summary>
        public static string BookingDate {
            get {
                return ResourceManager.GetString("BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking No. .
        /// </summary>
        public static string BookingNo {
            get {
                return ResourceManager.GetString("BookingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking No. Prefix .
        /// </summary>
        public static string BookingNumPrefix {
            get {
                return ResourceManager.GetString("BookingNumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code .
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel .
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add.
        /// </summary>
        public static string CantAdd {
            get {
                return ResourceManager.GetString("CantAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete.
        /// </summary>
        public static string CantDelete {
            get {
                return ResourceManager.GetString("CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit.
        /// </summary>
        public static string CantEdit {
            get {
                return ResourceManager.GetString("CantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Edit Invoiced Charge .
        /// </summary>
        public static string CantEditInvoicedCharge {
            get {
                return ResourceManager.GetString("CantEditInvoicedCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start this application from Freight Master Menu.
        /// </summary>
        public static string CantStartApp {
            get {
                return ResourceManager.GetString("CantStartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Description .
        /// </summary>
        public static string CargoDesc {
            get {
                return ResourceManager.GetString("CargoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Weight .
        /// </summary>
        public static string CargoWeight {
            get {
                return ResourceManager.GetString("CargoWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Agent .
        /// </summary>
        public static string CarrierAgent {
            get {
                return ResourceManager.GetString("CarrierAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBM.
        /// </summary>
        public static string CBM {
            get {
                return ResourceManager.GetString("CBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Code .
        /// </summary>
        public static string ChargeCode {
            get {
                return ResourceManager.GetString("ChargeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Description .
        /// </summary>
        public static string ChargeDescription {
            get {
                return ResourceManager.GetString("ChargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Details .
        /// </summary>
        public static string ChargeDetail {
            get {
                return ResourceManager.GetString("ChargeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge ID .
        /// </summary>
        public static string ChargeID {
            get {
                return ResourceManager.GetString("ChargeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Status .
        /// </summary>
        public static string ChargeStatus {
            get {
                return ResourceManager.GetString("ChargeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Type .
        /// </summary>
        public static string ChargeType {
            get {
                return ResourceManager.GetString("ChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City .
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close .
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code .
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Reg. No. .
        /// </summary>
        public static string CompanyRegNo {
            get {
                return ResourceManager.GetString("CompanyRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Complete Date : &apos;{0}&apos;.
        /// </summary>
        public static string ComplationDateRemark {
            get {
                return ResourceManager.GetString("ComplationDateRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed .
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation! .
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change trailer number ?.
        /// </summary>
        public static string ConfirmToChangeTrailerNo {
            get {
                return ResourceManager.GetString("ConfirmToChangeTrailerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the form?.
        /// </summary>
        public static string ConfirmToCloseForm {
            get {
                return ResourceManager.GetString("ConfirmToCloseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        public static string ConfirmToDeleteHeaderName {
            get {
                return ResourceManager.GetString("ConfirmToDeleteHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to proceed? .
        /// </summary>
        public static string ConfirmToProceed {
            get {
                return ResourceManager.GetString("ConfirmToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm To Set From Booked To Ready .
        /// </summary>
        public static string ConfirmToSetFromBookedToReady {
            get {
                return ResourceManager.GetString("ConfirmToSetFromBookedToReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee Code .
        /// </summary>
        public static string ConsigneeCode {
            get {
                return ResourceManager.GetString("ConsigneeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee Name .
        /// </summary>
        public static string ConsigneeName {
            get {
                return ResourceManager.GetString("ConsigneeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Code .
        /// </summary>
        public static string ContainerCode {
            get {
                return ResourceManager.GetString("ContainerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Size Code .
        /// </summary>
        public static string ContainerSizeCode {
            get {
                return ResourceManager.GetString("ContainerSizeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Yard .
        /// </summary>
        public static string ContainerYard {
            get {
                return ResourceManager.GetString("ContainerYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Days .
        /// </summary>
        public static string CreditDays {
            get {
                return ResourceManager.GetString("CreditDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit .
        /// </summary>
        public static string CreditLimit {
            get {
                return ResourceManager.GetString("CreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency .
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Amount.
        /// </summary>
        public static string CurrencyAmount {
            get {
                return ResourceManager.GetString("CurrencyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyCode .
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate .
        /// </summary>
        public static string CurrencyRate {
            get {
                return ResourceManager.GetString("CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust Code .
        /// </summary>
        public static string CustCode {
            get {
                return ResourceManager.GetString("CustCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust Name .
        /// </summary>
        public static string CustName {
            get {
                return ResourceManager.GetString("CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cust No .
        /// </summary>
        public static string CustNo {
            get {
                return ResourceManager.GetString("CustNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer .
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code .
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Group .
        /// </summary>
        public static string CustomerGroup {
            get {
                return ResourceManager.GetString("CustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name .
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date .
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Permit No 1 .
        /// </summary>
        public static string DatePermitNo1 {
            get {
                return ResourceManager.GetString("DatePermitNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Permit No 2 .
        /// </summary>
        public static string DatePermitNo2 {
            get {
                return ResourceManager.GetString("DatePermitNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days .
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete this selected record? .
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully .
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note .
        /// </summary>
        public static string DeliveryNote {
            get {
                return ResourceManager.GetString("DeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description .
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination .
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details .
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No .
        /// </summary>
        public static string DetailSeqNo {
            get {
                return ResourceManager.GetString("DetailSeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DG Remarks .
        /// </summary>
        public static string DGRemakrs {
            get {
                return ResourceManager.GetString("DGRemakrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Wish To Set To Complete .
        /// </summary>
        public static string DoYouWishToSetToComplete {
            get {
                return ResourceManager.GetString("DoYouWishToSetToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver .
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date .
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit .
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Succesfully .
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End .
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Cost .
        /// </summary>
        public static string EstimatedCost {
            get {
                return ResourceManager.GetString("EstimatedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA .
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETD .
        /// </summary>
        public static string ETD {
            get {
                return ResourceManager.GetString("ETD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate .
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempted .
        /// </summary>
        public static string Exempted {
            get {
                return ResourceManager.GetString("Exempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC .
        /// </summary>
        public static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Date .
        /// </summary>
        public static string FlightDate {
            get {
                return ResourceManager.GetString("FlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight No .
        /// </summary>
        public static string FlightNo {
            get {
                return ResourceManager.GetString("FlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross CBM .
        /// </summary>
        public static string GrossCBM {
            get {
                return ResourceManager.GetString("GrossCBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Profit .
        /// </summary>
        public static string GrossProfit {
            get {
                return ResourceManager.GetString("GrossProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Weight .
        /// </summary>
        public static string GrossWt {
            get {
                return ResourceManager.GetString("GrossWt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gst Amount HC .
        /// </summary>
        public static string GstAmountHC {
            get {
                return ResourceManager.GetString("GstAmountHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gst Rate .
        /// </summary>
        public static string GsTRate {
            get {
                return ResourceManager.GetString("GsTRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Reg. No. .
        /// </summary>
        public static string GSTRegNo {
            get {
                return ResourceManager.GetString("GSTRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gst Type .
        /// </summary>
        public static string GstType {
            get {
                return ResourceManager.GetString("GstType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAWB .
        /// </summary>
        public static string HAWB {
            get {
                return ResourceManager.GetString("HAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBL No .
        /// </summary>
        public static string HBLNo {
            get {
                return ResourceManager.GetString("HBLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home .
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC / Passport No .
        /// </summary>
        public static string ICNo {
            get {
                return ResourceManager.GetString("ICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC / Passport Type .
        /// </summary>
        public static string ICType {
            get {
                return ResourceManager.GetString("ICType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important .
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information!.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inval User.
        /// </summary>
        public static string InvadidUser {
            get {
                return ResourceManager.GetString("InvadidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login .
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice .
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice item .
        /// </summary>
        public static string InvoiceItem {
            get {
                return ResourceManager.GetString("InvoiceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No. .
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number .
        /// </summary>
        public static string InvoiceNumber {
            get {
                return ResourceManager.GetString("InvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceType .
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing .
        /// </summary>
        public static string Invoicing {
            get {
                return ResourceManager.GetString("Invoicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsSectorDependent .
        /// </summary>
        public static string IsSectorDependent {
            get {
                return ResourceManager.GetString("IsSectorDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Charge .
        /// </summary>
        public static string JobCharge {
            get {
                return ResourceManager.GetString("JobCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Detail .
        /// </summary>
        public static string JobDetail {
            get {
                return ResourceManager.GetString("JobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Entry .
        /// </summary>
        public static string JobEntry {
            get {
                return ResourceManager.GetString("JobEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOB ID .
        /// </summary>
        public static string JobId {
            get {
                return ResourceManager.GetString("JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No. .
        /// </summary>
        public static string JobNo {
            get {
                return ResourceManager.GetString("JobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No. Prefix .
        /// </summary>
        public static string JobNumPrefix {
            get {
                return ResourceManager.GetString("JobNumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Seq.
        /// </summary>
        public static string JobSeq {
            get {
                return ResourceManager.GetString("JobSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Trip .
        /// </summary>
        public static string JobTrip {
            get {
                return ResourceManager.GetString("JobTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Quotation Only .
        /// </summary>
        public static string LatestQuotationOnly {
            get {
                return ResourceManager.GetString("LatestQuotationOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local .
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log No. .
        /// </summary>
        public static string LogNo {
            get {
                return ResourceManager.GetString("LogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking .
        /// </summary>
        public static string Marking {
            get {
                return ResourceManager.GetString("Marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master .
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAWB .
        /// </summary>
        public static string MAWB {
            get {
                return ResourceManager.GetString("MAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded maximum length..
        /// </summary>
        public static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality .
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New .
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None .
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Quotation .
        /// </summary>
        public static string NoQuotation {
            get {
                return ResourceManager.GetString("NoQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Quotation for the seleted customer .
        /// </summary>
        public static string NoQuotationNoFound {
            get {
                return ResourceManager.GetString("NoQuotationNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record for DELETING .
        /// </summary>
        public static string NoRecordforDelete {
            get {
                return ResourceManager.GetString("NoRecordforDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record for EDITING .
        /// </summary>
        public static string NoRecordforEdit {
            get {
                return ResourceManager.GetString("NoRecordforEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoRecordFound .
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal .
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed .
        /// </summary>
        public static string NotCompleted {
            get {
                return ResourceManager.GetString("NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice!.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null reference been used!.
        /// </summary>
        public static string NULLReference {
            get {
                return ResourceManager.GetString("NULLReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBL No .
        /// </summary>
        public static string OBLNo {
            get {
                return ResourceManager.GetString("OBLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK .
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old .
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. Program aborted..
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin .
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Scope .
        /// </summary>
        public static string OutOfScope {
            get {
                return ResourceManager.GetString("OutOfScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit .
        /// </summary>
        public static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Detail .
        /// </summary>
        public static string PermitDetail {
            get {
                return ResourceManager.GetString("PermitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit No 1 .
        /// </summary>
        public static string PermitNo1 {
            get {
                return ResourceManager.GetString("PermitNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit No 2 .
        /// </summary>
        public static string PermitNo2 {
            get {
                return ResourceManager.GetString("PermitNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD .
        /// </summary>
        public static string POD {
            get {
                return ResourceManager.GetString("POD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POL .
        /// </summary>
        public static string POL {
            get {
                return ResourceManager.GetString("POL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port .
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted .
        /// </summary>
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview .
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print .
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print All .
        /// </summary>
        public static string PrintAll {
            get {
                return ResourceManager.GetString("PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Option .
        /// </summary>
        public static string PrintOption {
            get {
                return ResourceManager.GetString("PrintOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSA A/C No .
        /// </summary>
        public static string PSA {
            get {
                return ResourceManager.GetString("PSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query .
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation .
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Date .
        /// </summary>
        public static string QuotationDate {
            get {
                return ResourceManager.GetString("QuotationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Entry .
        /// </summary>
        public static string QuotationEntry {
            get {
                return ResourceManager.GetString("QuotationEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoutation ID .
        /// </summary>
        public static string QuotationID {
            get {
                return ResourceManager.GetString("QuotationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation No .
        /// </summary>
        public static string QuotationNo {
            get {
                return ResourceManager.GetString("QuotationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Type .
        /// </summary>
        public static string QuotationType {
            get {
                return ResourceManager.GetString("QuotationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate .
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type .
        /// </summary>
        public static string RateType {
            get {
                return ResourceManager.GetString("RateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks .
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales .
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Account Code .
        /// </summary>
        public static string SalesAcctCode {
            get {
                return ResourceManager.GetString("SalesAcctCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman .
        /// </summary>
        public static string Salesman {
            get {
                return ResourceManager.GetString("Salesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Save First. .
        /// </summary>
        public static string SaveFirst {
            get {
                return ResourceManager.GetString("SaveFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successfullly .
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Freight Detail .
        /// </summary>
        public static string SeaFreightDetail {
            get {
                return ResourceManager.GetString("SeaFreightDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Job .
        /// </summary>
        public static string SeaJob {
            get {
                return ResourceManager.GetString("SeaJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Job Container .
        /// </summary>
        public static string SeaJobContainer {
            get {
                return ResourceManager.GetString("SeaJobContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search .
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Code .
        /// </summary>
        public static string SectorCode {
            get {
                return ResourceManager.GetString("SectorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No .
        /// </summary>
        public static string SeqNo {
            get {
                return ResourceManager.GetString("SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Ref No. .
        /// </summary>
        public static string SourceRefNo {
            get {
                return ResourceManager.GetString("SourceRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Prefix .
        /// </summary>
        public static string SpecialPreFix {
            get {
                return ResourceManager.GetString("SpecialPreFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard .
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start .
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status .
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal .
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax .
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable .
        /// </summary>
        public static string Taxable {
            get {
                return ResourceManager.GetString("Taxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code .
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount .
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount FC .
        /// </summary>
        public static string TotalAmountFC {
            get {
                return ResourceManager.GetString("TotalAmountFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount HC .
        /// </summary>
        public static string TotalAmountHC {
            get {
                return ResourceManager.GetString("TotalAmountHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No. .
        /// </summary>
        public static string TrxNo {
            get {
                return ResourceManager.GetString("TrxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCR No .
        /// </summary>
        public static string UCRNo {
            get {
                return ResourceManager.GetString("UCRNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Amount .
        /// </summary>
        public static string UnitAmount {
            get {
                return ResourceManager.GetString("UnitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Rate .
        /// </summary>
        public static string UnitRate {
            get {
                return ResourceManager.GetString("UnitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Rate FC .
        /// </summary>
        public static string UnitRateFC {
            get {
                return ResourceManager.GetString("UnitRateFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Weight .
        /// </summary>
        public static string UnitWeight {
            get {
                return ResourceManager.GetString("UnitWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM .
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper .
        /// </summary>
        public static string Upper {
            get {
                return ResourceManager.GetString("Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent .
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select another ChargeCode or UOM or you may change the description .
        /// </summary>
        public static string ValidateNewJobCharge {
            get {
                return ResourceManager.GetString("ValidateNewJobCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From .
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To .
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel No .
        /// </summary>
        public static string VesselNo {
            get {
                return ResourceManager.GetString("VesselNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume .
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Capacity .
        /// </summary>
        public static string VolumeCapacity {
            get {
                return ResourceManager.GetString("VolumeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voyage No .
        /// </summary>
        public static string VoyageNo {
            get {
                return ResourceManager.GetString("VoyageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse No .
        /// </summary>
        public static string WarehouseNo {
            get {
                return ResourceManager.GetString("WarehouseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! .
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to exit the form?.
        /// </summary>
        public static string WarnningExit {
            get {
                return ResourceManager.GetString("WarnningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will resfresh all data from database, all unsaved data in memory will be lost..
        /// </summary>
        public static string WarnToRefreshData {
            get {
                return ResourceManager.GetString("WarnToRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight .
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Holding .
        /// </summary>
        public static string WithHolding {
            get {
                return ResourceManager.GetString("WithHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes .
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ref No .
        /// </summary>
        public static string YourRefNo {
            get {
                return ResourceManager.GetString("YourRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Rated .
        /// </summary>
        public static string ZeroRated {
            get {
                return ResourceManager.GetString("ZeroRated", resourceCulture);
            }
        }
    }
}
