//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR_LanguageResource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TptResourceDAL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TptResourceDAL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TR_LanguageResource.Resources.TptResourceDAL", typeof(TptResourceDAL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver hasn&apos;t been set.
        /// </summary>
        public static string DriverHasntSet {
            get {
                return ResourceManager.GetString("DriverHasntSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId &apos;{0}&apos; has been logout from the server. Please restart FM and login again..
        /// </summary>
        public static string ErrAccessingFMLogin {
            get {
                return ResourceManager.GetString("ErrAccessingFMLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not set correctly. Please exit FM and login again .
        /// </summary>
        public static string ErrDatabaseNotSet {
            get {
                return ResourceManager.GetString("ErrDatabaseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete.
        /// </summary>
        public static string ErrDeleteFailed {
            get {
                return ResourceManager.GetString("ErrDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to update.
        /// </summary>
        public static string ErrEditFailed {
            get {
                return ResourceManager.GetString("ErrEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to insert new priceBreakRange in AddPriceBreakRange in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToAddPriceBreaks {
            get {
                return ResourceManager.GetString("ErrFailedToAddPriceBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to insert new quotation header in AddQuotationHeader in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToAddQuotationHeader {
            get {
                return ResourceManager.GetString("ErrFailedToAddQuotationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to insert new quotation rate and pricebreaks in AddTransportRate in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToAddTransportRate {
            get {
                return ResourceManager.GetString("ErrFailedToAddTransportRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete priceBreakRange in DeletePriceBreakRange in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToDeletePriceBreaks {
            get {
                return ResourceManager.GetString("ErrFailedToDeletePriceBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete quotation header in EditQuotationHeader in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToDeleteQuotationHeader {
            get {
                return ResourceManager.GetString("ErrFailedToDeleteQuotationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to delete quotation rate in DeleteTransportRate in TransportMarketDAL  class.
        /// </summary>
        public static string ErrFailedToDeleteTransportRate {
            get {
                return ResourceManager.GetString("ErrFailedToDeleteTransportRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to edit priceBreakRange in EditPriceBreakRange in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToEditPriceBreaks {
            get {
                return ResourceManager.GetString("ErrFailedToEditPriceBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to edit quotation header in EditQuotationHeader in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToEditQuotationHeader {
            get {
                return ResourceManager.GetString("ErrFailedToEditQuotationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to edit quotation rate in EditTransportRate in TransportMarketDAL class.
        /// </summary>
        public static string ErrFailedToEditTransportRate {
            get {
                return ResourceManager.GetString("ErrFailedToEditTransportRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to save or insert.
        /// </summary>
        public static string ErrInsertFailed {
            get {
                return ResourceManager.GetString("ErrInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - More than 1 record deleted.
        /// </summary>
        public static string ErrMoreThan1RecordDeleted {
            get {
                return ResourceManager.GetString("ErrMoreThan1RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been changed by someone else. Please refresh the data and update.
        /// </summary>
        public static string ErrMultiUserConflict {
            get {
                return ResourceManager.GetString("ErrMultiUserConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - No record deleted.
        /// </summary>
        public static string ErrNoRecordDeleted {
            get {
                return ResourceManager.GetString("ErrNoRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Row Updated.
        /// </summary>
        public static string ErrNoRowUpdated {
            get {
                return ResourceManager.GetString("ErrNoRowUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Job Trip has more than one job trip sub-con..
        /// </summary>
        public static string MultiJobTripSubCon {
            get {
                return ResourceManager.GetString("MultiJobTripSubCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no such truck job trip.
        /// </summary>
        public static string NoSuchJobTrip {
            get {
                return ResourceManager.GetString("NoSuchJobTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator arranged truck capacity hasn&apos;t been set.
        /// </summary>
        public static string OprTruckCapHasntSet {
            get {
                return ResourceManager.GetString("OprTruckCapHasntSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set job trip to complete when its sub-con data is not completed.
        /// </summary>
        public static string SubConDataInComplete {
            get {
                return ResourceManager.GetString("SubConDataInComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following job trips are not completed.
        /// </summary>
        public static string TheFollowingJobTripsNotComplete {
            get {
                return ResourceManager.GetString("TheFollowingJobTripsNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle hasn&apos;t been set.
        /// </summary>
        public static string VehicleHasntSet {
            get {
                return ResourceManager.GetString("VehicleHasntSet", resourceCulture);
            }
        }
    }
}
