//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TR_LanguageResource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TptResourceReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TptResourceReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TR_LanguageResource.Resources.TptResourceReport", typeof(TptResourceReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records. Please choose another search criteria .
        /// </summary>
        public static string ErrCriteriaNoRecordFound {
            get {
                return ResourceManager.GetString("ErrCriteriaNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have rights to view this report. .
        /// </summary>
        public static string ErrNoAccessRight {
            get {
                return ResourceManager.GetString("ErrNoAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Booking Confirmation found in this job. You may select another job. .
        /// </summary>
        public static string ErrNoBookingConfirmationFound {
            get {
                return ResourceManager.GetString("ErrNoBookingConfirmationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delivery Note found in this job. You may select another job. .
        /// </summary>
        public static string ErrNoDeliveryNoteFound {
            get {
                return ResourceManager.GetString("ErrNoDeliveryNoteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Confirmation Report .
        /// </summary>
        public static string RptBookingConfirmation {
            get {
                return ResourceManager.GetString("RptBookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Advice Report .
        /// </summary>
        public static string RptCollectionAdvice {
            get {
                return ResourceManager.GetString("RptCollectionAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Stamp .
        /// </summary>
        public static string RptCompanyStamp {
            get {
                return ResourceManager.GetString("RptCompanyStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Jobs by Date and Customer .
        /// </summary>
        public static string RptCompletedJobsbyDateAndCustomer {
            get {
                return ResourceManager.GetString("RptCompletedJobsbyDateAndCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Jobs by Date and Driver Report .
        /// </summary>
        public static string RptCompletedJobsbyDateAndDriver {
            get {
                return ResourceManager.GetString("RptCompletedJobsbyDateAndDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Due Date Report .
        /// </summary>
        public static string RptContainerDueDate {
            get {
                return ResourceManager.GetString("RptContainerDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Moved Details Report .
        /// </summary>
        public static string RptContainerMovedDetails {
            get {
                return ResourceManager.GetString("RptContainerMovedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customure By Job Value Report .
        /// </summary>
        public static string RptCustomerByJobValue {
            get {
                return ResourceManager.GetString("RptCustomerByJobValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Signature .
        /// </summary>
        public static string RptCustomerSignature {
            get {
                return ResourceManager.GetString("RptCustomerSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date .
        /// </summary>
        public static string RptDate {
            get {
                return ResourceManager.GetString("RptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Completed .
        /// </summary>
        public static string RptDateCompleted {
            get {
                return ResourceManager.GetString("RptDateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Printed.
        /// </summary>
        public static string RptDatePrinted {
            get {
                return ResourceManager.GetString("RptDatePrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered By .
        /// </summary>
        public static string RptDeliveredBy {
            get {
                return ResourceManager.GetString("RptDeliveredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Date .
        /// </summary>
        public static string RptDeliveredDate {
            get {
                return ResourceManager.GetString("RptDeliveredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered From .
        /// </summary>
        public static string RptDeliveredFrom {
            get {
                return ResourceManager.GetString("RptDeliveredFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered To.
        /// </summary>
        public static string RptDeliveredTo {
            get {
                return ResourceManager.GetString("RptDeliveredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note Report.
        /// </summary>
        public static string RptDeliveryNote {
            get {
                return ResourceManager.GetString("RptDeliveryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order Report.
        /// </summary>
        public static string RptDeliveryOrder {
            get {
                return ResourceManager.GetString("RptDeliveryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation .
        /// </summary>
        public static string RptDesignation {
            get {
                return ResourceManager.GetString("RptDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haulier Job Report.
        /// </summary>
        public static string RptHualierJob {
            get {
                return ResourceManager.GetString("RptHualierJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        public static string RptJobDetail {
            get {
                return ResourceManager.GetString("RptJobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Summary Report.
        /// </summary>
        public static string RptJobSummary {
            get {
                return ResourceManager.GetString("RptJobSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Trip Details Report.
        /// </summary>
        public static string RptJobTripDetails {
            get {
                return ResourceManager.GetString("RptJobTripDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Trips By Customer Report.
        /// </summary>
        public static string RptJobTripsByCust {
            get {
                return ResourceManager.GetString("RptJobTripsByCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Trips Sub Con Report.
        /// </summary>
        public static string RptJobTripSubCon {
            get {
                return ResourceManager.GetString("RptJobTripSubCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Value By Customer Report.
        /// </summary>
        public static string RptJobValueByCust {
            get {
                return ResourceManager.GetString("RptJobValueByCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job With Invoice Report.
        /// </summary>
        public static string RptJobWithInvoice {
            get {
                return ResourceManager.GetString("RptJobWithInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Jobs .
        /// </summary>
        public static string RptNoOfJobs {
            get {
                return ResourceManager.GetString("RptNoOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Trips .
        /// </summary>
        public static string RptNoOfTrips {
            get {
                return ResourceManager.GetString("RptNoOfTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record found to print. .
        /// </summary>
        public static string RptNoRecordFoundtoPrint {
            get {
                return ResourceManager.GetString("RptNoRecordFoundtoPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string RptPage {
            get {
                return ResourceManager.GetString("RptPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Trip By Date Report.
        /// </summary>
        public static string RptPlanTripByDate {
            get {
                return ResourceManager.GetString("RptPlanTripByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received By.
        /// </summary>
        public static string RptReceivedBy {
            get {
                return ResourceManager.GetString("RptReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date .
        /// </summary>
        public static string RptReceivedDate {
            get {
                return ResourceManager.GetString("RptReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string RptReportDate {
            get {
                return ResourceManager.GetString("RptReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string RptSubTotal {
            get {
                return ResourceManager.GetString("RptSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string RptTotal {
            get {
                return ResourceManager.GetString("RptTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbilled Jobs Report.
        /// </summary>
        public static string RptUnbilledJobs {
            get {
                return ResourceManager.GetString("RptUnbilledJobs", resourceCulture);
            }
        }
    }
}
